name: Swift on Mac
on: 
 push: 
   branches: ["main"]

jobs:
  build:
    name: Swift on Mac-OS 
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.5.0", "5.6.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v3
    - name: Build
      run: swift build --build-tests
    - name: Run tests
      run: swift test
