name: Mac-OS
on: 
 push: 
   branches: ["main"]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14, macos-latest]
        swift: ["5.5", "5.6", "5.7"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
