name: Swift for older
on: 
 push: 
   branches: ["main"]
jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        swift: [5.5, 5.6, 5.7]
        os: [ubuntu-20.04, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Build
      run: swift build
    - name: Run Tests
      run: swift test
