name: Swift on Windows 

on:
  push:
    branches: [ main ]

jobs:
  Test:
    name: Execute tests on Windows
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.5", "5.6", "5.7"]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          swift-version: ${{ matrix.swift_version }}
